version: "3.9"

services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: ['yarn', 'dev', '--host', '0.0.0.0', '--port', '8080']